{% set name = "colorlog" %}
{% set version = "6.9.0" %}

package:
  name: colorlog
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colorlog-{{ version }}.tar.gz
  sha256: bfba54a1b93b94f54e1f4fe48395725a3d92fd2a4af702f6bd70946bdc0c6ac2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=38.6.0
    - colorama  # [win]

  run:
    - python
    - colorama  # [win]

test:
  imports:
    - colorlog
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/borntyping/python-colorlog
  license: MIT
  license_file: LICENSE
  summary: Log formatting with colors!

extra:
  recipe-maintainers:
    - xylar
    - frol
    - forrestwaters
