{% set version = "4.8.0" %}

package:
  name: colorlog
  version: {{ version }}

source:
  fn: colorlog-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/c/colorlog/colorlog-{{ version }}.tar.gz
  sha256: 59b53160c60902c405cdec28d38356e09d40686659048893e026ecbd589516b1

build:
  number: 0
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - colorama  # [win]

  run:
    - python
    - colorama  # [win]

test:
  imports:
    - colorlog

about:
  home: https://github.com/borntyping/python-colorlog
  license: MIT
  license_file: LICENSE
  summary: Log formatting with colors!

extra:
  recipe-maintainers:
    - frol
    - forrestwaters
