{% set name = "colorlog" %}
{% set version = "6.10.1" %}

package:
  name: colorlog
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/colorlog-{{ version }}.tar.gz
  sha256: eb4ae5cb65fe7fec7773c2306061a8e63e02efc2c72eba9d27b0fa23c94f1321

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=38.6.0
    - colorama  # [win]

  run:
    - python >={{ python_min }}
    - __unix  # [unix]
    - __win   # [win]
    - colorama  # [win]

test:
  imports:
    - colorlog
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/borntyping/python-colorlog
  license: MIT
  license_file: LICENSE
  summary: Log formatting with colors!

extra:
  recipe-maintainers:
    - xylar
    - frol
    - forrestwaters
