{% set version = "6.7.0" %}

package:
  name: colorlog
  version: {{ version }}

source:
  fn: colorlog-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/c/colorlog/colorlog-{{ version }}.tar.gz
  sha256: bd94bd21c1e13fac7bd3153f4bc3a7dc0eb0974b8bc2fdf1a989e474f6e582e5

build:
  number: 1
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - colorama  # [win]

  run:
    - python
    - colorama  # [win]

test:
  imports:
    - colorlog

about:
  home: https://github.com/borntyping/python-colorlog
  license: MIT
  license_file: LICENSE
  summary: Log formatting with colors!

extra:
  recipe-maintainers:
    - xylar
    - frol
    - forrestwaters
